# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew docker git git-flow mercurial pip python)

source $ZSH/oh-my-zsh.sh

# User configuration
source $HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme
source /Users/dmilburn/.utilFunctions.sh

export PATH=$PATH:/Users/dmilburn/src/projects/gitplus/commands
export GIT_MERGE_AUTOEDIT=no
export PATH=$PATH:$HOME/.nodenv/shims
export PATH=$PATH:/opt/vertica/bin
export ANSIBLE_ENV_PATH=/Users/dmilburn/src/projects/Ansible-Environments

[ -f /opt/hamurai/env.sh ] && source /opt/hamurai/env.sh
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/dmilburn/.nodenv/versions/8.9.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/dmilburn/.nodenv/versions/8.9.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/dmilburn/.nodenv/versions/8.9.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/dmilburn/.nodenv/versions/8.9.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
export PATH="/usr/local/sbin:$PATH"
